# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: pages.virtualgoodsdealer.com
author: virtualgoodsdealer
email: virtualgoodsofficial@gmail.com
description: >- # this means to ignore newlines until "baseurl:" 
  virtualgoodsdealer is a collaborative virtual space and e-commerce portal. working in art, fashion, technology, and craft, we provide an infrastructure to facilitate creative trades and develop products. pages.virtualgoodsdealer.com focuses on publishing non-physical art and showcasing creators. by ada.wrong, cindie xin, and saqmemes.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://pages.virtualgoodsdealer.com" # the base hostname & protocol for your site, e.g. http://example.com

shop: https://products.virtualgoodsdealer.com

# Build settings
remote_theme: aidewoode/jekyll-theme-mint
future: true

blog_theme: light

permalink: /articles/:year/:month/:day/:title/

# generate social links in footer
social_links:
  twitter: vgddotcom
#  github: virtualgoodsdealer
  # facebook: jekyll
  instagram: virtualgoodsdealer
  # linkedin: jekyll
  # pinterest: jekyll
  # youtube: jekyll
  youtube_channel: UC7nl2wkFLvyrxZtwfr6s2CA
  youtube_channel_name: virtualgoodsdealer

  # Mastodon instances
  # mastodon:
  # - username: jekyll
  #   instance: example.com
  # - username: jekyll2
  #   instance: example.com

# article categories set up
# artist directory set up

collections:
  category:
    output: true
  creators:
    output: true
  submissions:
    output: true
  deleted2020:
    output: true

defaults:
  - scope:
      path: ""
      type: "category"
    values:
      layout: "articles"
  - scope:
      path: ""
      type: "creators"
    values:
      layout: "creator"
  - scope:
      path: ""
      type: "submissions"
    values:
      layout: "submissions"
  - scope:
      path: ""
      type: "deleted2020"
    values:
      layout: "deleted2020redirect"
      title: "Deleted in 2020"


google_analytics: G-VTKW4XE2X9

feed:
  collections:
    - creators
    - submissions

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
